### ISSUE TITLE
Создание дорожной карты согласно приложенной документации

### ISSUE THREAD

**Issue by yershova-margarita** [dlsingle/messenger#2]
[Создание эффективной дорожной карты.pdf](https://github.com/user-attachments/files/17011939/default.pdf)
[Пример 9 к лекции 1.pdf](https://github.com/user-attachments/files/17011945/9.1.pdf)

https://github.com/dlsingle/messenger/issues/2#issue-2528174114

**Comment by Kuan67-sml** [comment]
[Дорожная карта.docx](https://github.com/user-attachments/files/17798664/default.docx)
Готово
