### ISSUE TITLE
Создание проектного плана, согласно приложенной документации

### ISSUE THREAD

**Issue by yershova-margarita** [dlsingle/messenger#3]
[Разработка проектного плана.pdf](https://github.com/user-attachments/files/17012012/default.pdf)
[Пример 8 к лекции 1.pdf](https://github.com/user-attachments/files/17012019/8.1.pdf)

Deadline: 30.09.2024

**Comment by Kuan67-sml** [comment]
[Проектный план.docx](https://github.com/user-attachments/files/17798692/default.docx)
Готово
